name: GitHub Actions Demo pytest
run-name: ${{ github.action }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-Github-Actions-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.8"]
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .'[dev]'
      - name: Test with pytest
        run: |
          python3 -m pytest
